# Generated by Django 4.0.3 on 2022-03-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gem_id', models.PositiveSmallIntegerField()),
                ('message_payload', models.JSONField()),
            ],
        ),
    ]
