# Generated by Django 4.0.3 on 2022-03-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgrestry', '0002_rename_greeting_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='discord_username',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sign',
            name='hackernews_username',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sign',
            name='wallet_address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
