# Generated by Django 4.0.3 on 2022-03-30 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MySimpleModel',
            new_name='SimpleModel',
        ),
    ]
